language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - libasound2-dev
            - libgtk2.0-dev
            - g++-7
            - wget
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
 - wget https://vcvrack.com/downloads/Rack-SDK-0.6.0.zip 
 - unzip Rack-SDK-0.6.0.zip
 - eval "${MATRIX_EVAL}"

script:
 - RACK_DIR=./Rack-SDK/ make dist
